spring:
  profiles:
    active:
      - dev
---
spring:
  profiles:
    application:
      name: microservicecloud-config-perfyschu-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-perfyschu-test